export const PostData = [
  {
    userId: 1,
    userName: 'Alice Johnson',
    userAvatar: 'https://randomuser.me/api/portraits/women/70.jpg',
    followers: 150,
    following: 100,
    shortBio: 'Adventure enthusiast | Beach lover',
    postContent: 'Having a great day at the beach!',
    postImages: [
      'https://picsum.photos/id/1040/800/1200',
      'https://picsum.photos/id/1041/800/1200',
      'https://picsum.photos/id/1042/800/1200',
    ],
    comments: [
      {commentId: 1, commenterName: 'Bob', commentText: 'Beautiful view!'},
      {commentId: 2, commenterName: 'Charlie', commentText: 'Looks amazing!'},
    ],
    likes: 23,
  },
  {
    userId: 2,
    userName: 'John Smith',
    userAvatar: 'https://randomuser.me/api/portraits/men/72.jpg',
    followers: 200,
    following: 120,
    shortBio: 'City explorer | #Adventures',
    postContent: 'Exploring the city streets. #Adventures',
    postImages: [
      'https://picsum.photos/id/1043/800/1200',
      'https://picsum.photos/id/1044/800/1200',
      'https://picsum.photos/id/1045/800/1200',
    ],
    comments: [
      {
        commentId: 1,
        commenterName: 'Alice',
        commentText: 'Love the city vibes!',
      },
      {commentId: 2, commenterName: 'Eva', commentText: 'Awesome photos!'},
    ],
    likes: 45,
  },
  {
    userId: 3,
    userName: 'Sophia Williams',
    userAvatar: 'https://randomuser.me/api/portraits/women/74.jpg',
    followers: 120,
    following: 80,
    shortBio: 'Book lover | Cozy evenings',
    postContent: 'Enjoying a cozy evening with a good book.',
    postImages: [
      'https://picsum.photos/id/1049/800/1200',
      'https://picsum.photos/id/1047/800/1200',
      'https://picsum.photos/id/1048/800/1200',
    ],
    comments: [
      {
        commentId: 1,
        commenterName: 'Oliver',
        commentText: 'Looks so relaxing!',
      },
      {
        commentId: 2,
        commenterName: 'Emma',
        commentText: 'Perfect way to unwind.',
      },
    ],
    likes: 32,
  },
  {
    userId: 7,
    userName: 'Liam Turner',
    userAvatar: 'https://randomuser.me/api/portraits/men/85.jpg',
    followers: 180,
    following: 150,
    shortBio: 'Nature lover | Mountain climber',
    postContent: 'Climbing mountains and enjoying the view!',
    postImages: [
      'https://picsum.photos/id/1050/800/1200',
      'https://picsum.photos/id/1051/800/1200',
      'https://picsum.photos/id/1052/800/1200',
    ],
    comments: [
      {commentId: 1, commenterName: 'Ava', commentText: 'Amazing scenery!'},
      {
        commentId: 2,
        commenterName: 'Jack',
        commentText: 'Looks like a great adventure!',
      },
    ],
    likes: 56,
  },
  {
    userId: 8,
    userName: 'Emma White',
    userAvatar: 'https://randomuser.me/api/portraits/women/88.jpg',
    followers: 210,
    following: 180,
    shortBio: 'City explorer | Hidden gems',
    postContent: 'Exploring hidden gems in the city.',
    postImages: [
      'https://picsum.photos/id/1053/800/1200',
      'https://picsum.photos/id/1054/800/1200',
      'https://picsum.photos/id/1055/800/1200',
    ],
    comments: [
      {commentId: 1, commenterName: 'Noah', commentText: 'Love the cityscape!'},
      {
        commentId: 2,
        commenterName: 'Sophie',
        commentText: 'Adventurous spirit!',
      },
    ],
    likes: 41,
  },
  {
    userId: 9,
    userName: 'Olivia Davis',
    userAvatar: 'https://randomuser.me/api/portraits/women/90.jpg',
    followers: 190,
    following: 160,
    shortBio: 'Cozy evenings | Fireplace lover',
    postContent: 'Cozy evenings by the fireplace.',
    postImages: [
      'https://picsum.photos/id/1056/800/1200',
      'https://picsum.photos/id/1057/800/1200',
      'https://picsum.photos/id/1058/800/1200',
    ],
    comments: [
      {
        commentId: 1,
        commenterName: 'Ethan',
        commentText: 'Perfect relaxation spot!',
      },
      {
        commentId: 2,
        commenterName: 'Aria',
        commentText: 'Warm and inviting atmosphere.',
      },
    ],
    likes: 34,
  },
];
